# Generated by Django 4.0.5 on 2022-06-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_rename_firstname_userdetails_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
