# Generated by Django 4.0.5 on 2022-06-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0004_remove_userdetails_is_verified_userdetails_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(max_length=160),
        ),
    ]
