# Generated by Django 4.0.5 on 2022-06-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0006_useraddresss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddresss',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
