# Generated by Django 4.0.5 on 2022-06-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0007_alter_useraddresss_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='userCorrespondenceAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corres_house_number', models.CharField(max_length=50)),
                ('corres_landmark', models.CharField(max_length=100)),
                ('country1', models.CharField(max_length=50)),
                ('state1', models.CharField(max_length=50)),
                ('city1', models.CharField(max_length=100)),
                ('pincode1', models.IntegerField()),
            ],
        ),
    ]
