# Generated by Django 4.0.5 on 2022-06-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0008_usercorrespondenceaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddresss',
            name='user',
        ),
    ]
