# Generated by Django 4.0.5 on 2022-06-16 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0009_remove_useraddresss_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddresss',
            name='useradd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='otp.userdetails'),
        ),
    ]
