# Generated by Django 4.0.5 on 2022-06-16 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0010_useraddresss_useradd'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercorrespondenceaddress',
            name='useradd1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='otp.userdetails'),
        ),
        migrations.AddField(
            model_name='usercorrespondenceaddress',
            name='useradd2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='otp.useraddresss'),
        ),
    ]
