# Generated by Django 4.0.5 on 2022-06-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0011_usercorrespondenceaddress_useradd1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercorrespondenceaddress',
            name='useradd1',
        ),
        migrations.RemoveField(
            model_name='usercorrespondenceaddress',
            name='useradd2',
        ),
    ]
